project:
  type: website
  output-dir: docs

website:
  title: "Análisis de la Variancia"
  navbar:
    right:
      - text: Contenidos
        href: contenidos/index.qmd
        
  sidebar:
    - title: Contenidos
      style: docked
      search: false
      background: dark
      header: Contenidos
      contents:
        - text: Titulo 1
          file: contenidos/un_criterio.qmd
        - text: Titulo 2
          file: contenidos/dos_criterios_aditivos.qmd

format:
  html:
    theme: 
      - journal
      - styles.scss
    toc: true
    lang: es
